### ISSUE TITLE
Merge "multiple source tables & output tables supports" into master branch

### ISSUE THREAD

**Issue by weiqingy** [hortonworks-spark/spark-atlas-connector#11]

**Comment by weiqingy** [comment]
PR: https://github.com/hortonworks-spark/spark-atlas-connector/pull/15

**Comment by dongjoon-hyun** [comment]
This is merged at https://github.com/hortonworks-spark/spark-atlas-connector/commit/ad5a99d017b4caa1393681878e66a6c0daef503f
