### ISSUE TITLE
Change default client to Kafka

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks-spark/spark-atlas-connector#135]
Kafka provides durable and persistent storage which makes SAC able to provide updates even Atlas goes offline due to some reasons. Moreover, Kafka also provides enterprise security.

SAC is providing option to change the type of client as 'rest' and 'kafka'. Currently default value is 'rest', and it's worth to change default to 'kafka'.

**Comment by AmolKakade** [comment]
Hi Team,

I want to use spark-atlas connector with atlas.client.type as kafka on non-kerberos enabled cluster.
Is t possible? I tried running but I am not able to see lineage. By using atlas.client.type=rest I can see lineage.
