### ISSUE TITLE
Spark-atlas-connector 1.1 is not working

### ISSUE THREAD

**Issue by aemanukyan** [hortonworks-spark/spark-atlas-connector#277]
I've setup HDP 3.1 where includes Apache Atlas 1.1 and Apache Spark 2.3.
 I started to setup a connector and made everything as in readme, i.e I copied atlas-application.properties and put in $SPARK_HOME/conf, then I run the script for creating models: 
"java -cp "<spark dist>/jars/*:<spark dist>/conf:spark-atlas-connector_2.11-0.1.0-SNAPSHOT.jar" com.hortonworks.spark.atlas.types.SparkAtlasModel --interactive-auth"
  and I copied a zeppelin example and run it. Job worked but nothing appeared in the atlas.

**Comment by wannaberich** [comment]
The problem was about kafka-consuming. When hdp starts and you try to run zeppelin job, you won't see anything in apache atlas even you job completed successfully. You need to connect to kafka-broker and consume from topic ATLAS_HOOK. After that your data will be appeared.
