### ISSUE TITLE
Compilation failed, Could not resolve dependencies

### ISSUE THREAD

**Issue by Kartik1899** [hortonworks-spark/spark-atlas-connector#318]
`Could not resolve dependencies for project com.hortonworks.spark:spark-atlas-connector-main_2.11:pom:0.1.0-SNAPSHOT: Failed to collect dependencies at com.hotels:beeju:jar:1.3.1 -> org.apache.hive:hive-exec:jar:2.3.4 -> org.apache.calcite:calcite-core:jar:1.10.0 -> org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde: Failed to read artifact descriptor for org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde: Could not transfer artifact org.pentaho:pentaho-aggdesigner-algorithm:pom:5.1.5-jhyde from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [datanucleus (http://www.datanucleus.org/downloads/maven2, default, releases), glassfish-repository (http://maven.glassfish.org/content/groups/glassfish, default, disabled), glassfish-repo-archive (http://maven.glassfish.org/content/groups/glassfish, default, disabled), apache.snapshots (http://repository.apache.org/snapshots, default, snapshots), central (http://repo.maven.apache.org/maven2, default, releases), conjars (http://conjars.org/repo, default, releases+snapshots)]`

I'm using Maven version 3.8.3 and getting this error about missing repos. I've tried manually adding ` org.apache.hive:hive-exec:jar:2.3.4` `com.hotels:beeju:jar:1.3.1` `org.apache.calcite:calcite-core:jar:1.10.0`  `org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde` but it still throws this error 

`Failed to execute goal on project spark-atlas-connector-main_2.11: Could not resolve dependencies for project com.hortonworks.spark:spark-atlas-connector-main_2.11:pom:0.1.0-SNAPSHOT: Failed to collect dependencies at org.apache.hive:hive-exec:jar:2.3.4 -> org.apache.calcite:calcite-core:jar:1.10.0 -> org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde: Failed to read artifact descriptor for org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde: Could not transfer artifact org.pentaho:pentaho-aggdesigner-algorithm:pom:5.1.5-jhyde from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [spring-libs (http://repo.spring.io/libs-milestone/, default, releases+snapshots), datanucleus (http://www.datanucleus.org/downloads/maven2, default, releases), glassfish-repository (http://maven.glassfish.org/content/groups/glassfish, default, disabled), glassfish-repo-archive (http://maven.glassfish.org/content/groups/glassfish, default, disabled), apache.snapshots (http://repository.apache.org/snapshots, default, snapshots), central (http://repo.maven.apache.org/maven2, default, releases), conjars (http://conjars.org/repo, default, releases+snapshots)] ->`

Any solutions?

**Comment by Kartik1899** [comment]
Had to enable download from mirrors.

**Comment by maksiboi** [comment]
> Had to enable download from mirrors.

Can u pls tell me exactly where did u enable download?
Be more specific how did u solve it pls.
