### ISSUE TITLE
Question: spark initialization fails with java.lang.ClassNotFoundException: org.apache.atlas.ApplicationProperties 

### ISSUE THREAD

**Issue by pprasad009** [hortonworks-spark/spark-atlas-connector#35]
Hi, 

I have built the spark-atlas-connector_2.11-0.1.0-SNAPSHOT.jar as mentioned in the readme doc.

while i try to start the spark-shell --conf spark.extraListeners=com.hortonworks.spark.atlas.sql.SparkCatalogEventTracker property spark throws  following error

Caused by: java.lang.ClassNotFoundException: org.apache.atlas.ApplicationProperties

I've even tried adding atlas 0.8.2 jar explicitly while invoking spark-shell 

PFB command i'm executing
`spark-shell --jars ~/hadoop/spark/jars/spark-atlas-connector_2.11-0.1.0-SNAPSHOT.jar, ~/hadoop/spark/jars/atlas-distro-0.8.2.jar --conf spark.extraListeners=com.hortonworks.spark.atlas.sql.SparkCatalogEventTracker --files ~/hadoop/spark/conf/atlas-application.properties 
` 

can you please help me understanding what i'm missing?

Thanks!

![image](https://user-images.githubusercontent.com/20123973/37159186-31814dbc-2313-11e8-94db-acc4512b3528.png)

**Comment by jerryshao** [comment]
It means that you're missing atlas related dependencies. You need to use uber jar or put everything in your classpath.
