### ISSUE TITLE
Merge SparkExtension class into repo

### ISSUE THREAD

**Issue by weiqingy** [hortonworks-spark/spark-atlas-connector#7]
SparkExtension is used for showing user SQL queries.

**Comment by jerryshao** [comment]
@weiqingy I don't see the codes where you merged, or are you going to merge this?

**Comment by weiqingy** [comment]
@jerryshao  Sorry for the late reply. I donot know why I didn't get any github notification.

I have submitted a PR(https://github.com/hortonworks-spark/spark-atlas-connector/pull/10) for this.

**Comment by dongjoon-hyun** [comment]
This is merged at https://github.com/hortonworks-spark/spark-atlas-connector/commit/36ec1994bc2ed6b87dee69bd9f1ad27c126d4d35
